@Library('clientBuild') _

node {
    stage('info') {
        sh 'echo Building ${BRANCH_NAME}...'
    }
    stage('clean workspace') {
        cleanWs()
    }
    stage('get source') {
        checkout scm
    }
    stage('run client-build script') {
        clientBuild()
    }
    stage ('deploy assets to live server') {
        dir('static/clients/web') {
            sh 'sshpass -p Bettie123! ssh -o StrictHostKeyChecking=no kewin@coinpush.app rm -rf /home/kewin/Projects/CoinPush/static/clients/web'
            sh 'sshpass -p Bettie123! ssh -o StrictHostKeyChecking=no kewin@coinpush.app mkdir -p /home/kewin/Projects/CoinPush/static/clients/web'
            sh 'sshpass -p Bettie123! scp -rp ./ kewin@coinpush.app:/home/kewin/Projects/CoinPush/static/clients/web'
        }
    }
}