// @Library('clientBuild') _


node {
    stage('clean workspace') {
        // cleanWs()
    }
    stage('get source') {
        checkout scm
        // clientBuild()
        // load 'server-jenkins/pipelines/client-prod-build/Jenkinsfile'
    }
    // stage('build client through docker') {
    //      dir('./') { 
    //         sh 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml build client'
    //         sh 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml up client'
    //      }
    //     // sh 'npm run d-rmi-all'
       
    // }
    stage('remove docker container') {
        // sh 'docker rm client'
    }
    stage('build docker container') {
        dir('client') { 
             sh 'npm run build-prod-client'
        }
       
    }
    stage('build client through docker') {
         dir('client') { 
             sh 'npm run prod-client'
        }
       
    }
    // stage('remove docker container') {
    //     sh 'docker rm client'
    // }
    stage('enable maintenance mode on nginx') {
        sh 'sshpass -p Bettie123! ssh -o StrictHostKeyChecking=no kewin@coinpush.app cp /home/kewin/Projects/TradeJS/server-nginx/pages/maintenance_off.html /home/kewin/Projects/TradeJS/server-nginx/pages/maintenance_on.html'
    }
    stage ('deploy build assets to live server') {
        dir('static/clients/web') {
            sh 'sshpass -p Bettie123! ssh -o StrictHostKeyChecking=no kewin@coinpush.app rm -rf /home/kewin/Projects/TradeJS/static/clients/web'
            sh 'sshpass -p Bettie123! ssh -o StrictHostKeyChecking=no kewin@coinpush.app mkdir -p /home/kewin/Projects/TradeJS/static/clients/web'
            sh 'sshpass -p Bettie123! scp -rp ./ kewin@coinpush.app:/home/kewin/Projects/TradeJS/static/clients/web'
        }
    }
    stage('disable maintenance mode on nginx') {
        sh 'sshpass -p Bettie123! ssh -o StrictHostKeyChecking=no kewin@coinpush.app rm -f /home/kewin/Projects/TradeJS/server-nginx/pages/maintenance_on.html'
    }
}