"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * CLIENT
 */
exports.WINDOW_SIZE_MAX_MOBILE = 768, exports.WINDOW_SIZE_MAX_TABLET = 992, 
/**
 * SYSTEM
 */
exports.SYSTEM_STATE_BOOTING = -1, exports.SYSTEM_STATE_OK = 0, exports.SYSTEM_STATE_WARNING = 1, exports.SYSTEM_STATE_ERROR = 2, exports.SYSTEM_STATE_CODE_OK = 0, exports.SYSTEM_STATE_CODE_LOGIN = 1, exports.SYSTEM_STATE_CODE_BAD_BROKER_CONNECTION = 2, exports.SYSTEM_STATE_CODE_NO_BROKER_CONNECTION = 3, exports.SYSTEM_STATE_CODE_BAD_SERVER_CONNECTION = 4, exports.SYSTEM_STATE_CODE_NO_SERVER_CONNECTION = 5, 
/**
 * General error codes
 */
exports.G_ERROR_UNKNOWN = 0, exports.G_ERROR_EXPIRED = 1, exports.G_ERROR_DUPLICATE_CODE = 2, exports.G_ERROR_MAX_SIZE = 3, exports.G_ERROR_USER_NOT_FOUND = 100, 
/**
 * General mongo errors
 */
exports.G_ERROR_DUPLICATE_NAME = 'ValidationError', 
/**
 * ORDER
 */
exports.ORDER_SIDE_BUY = 0, exports.ORDER_SIDE_SELL = 1, exports.ORDER_TYPE_NONE = 0, exports.ORDER_TYPE_MARKET = 1, exports.ORDER_TYPE_LIMIT = 2, exports.ORDER_TYPE_STOP = 3, exports.ORDER_TYPE_IF_TOUCHED = 4, 
/**
 * Broker - General
 */
exports.BROKER_GENERAL_TYPE_NONE = 0, exports.BROKER_GENERAL_TYPE_OANDA = 1, exports.BROKER_GENERAL_TYPE_IB = 2, exports.BROKER_GENERAL_TYPE_CC = 3, exports.BROKER_GENERAL_TYPE_IEX = 4, 
/**
 * Broker - CoinPush
 */
exports.BROKER_ERROR_UNKNOWN = 0, exports.BROKER_ERROR_INVALID_ARGUMENT = 1, exports.BROKER_ERROR_MARKET_CLOSED = 2, exports.BROKER_ERROR_UNAUTHORIZED = 3, exports.BROKER_ERROR_DISCONNECT = 4, exports.BROKER_ERROR_PARSE = 5, exports.BROKER_ERROR_HEARTBEAT_TIMEOUT = 6, exports.BROKER_ERROR_HTTP = 7, exports.BROKER_ERROR_NOT_ENOUGH_FUNDS = 8, exports.BROKER_ERROR_TRADE_NOT_FOUND = 9, 
/**
 * Broker - OANDA
 */
exports.BROKER_OANDA_ERROR_INVALID_ARGUMENT = 1, exports.BROKER_OANDA_ERROR_MARKET_CLOSED = 24, exports.BROKER_OANDA_ERROR_TRADE_NOT_FOUND = 12, 
/**
 * Symbol
 */
exports.SYMBOL_CAT_TYPE_OTHER = 0, exports.SYMBOL_CAT_TYPE_FOREX = 1, exports.SYMBOL_CAT_TYPE_INDICE = 2, exports.SYMBOL_CAT_TYPE_CRYPTO = 3, exports.SYMBOL_CAT_TYPE_RESOURCE = 4, exports.SYMBOL_CAT_TYPE_OPTIONS = 5, exports.SYMBOL_CAT_TYPE_STOCK = 6, exports.SYMBOL_CAT_TYPE_COMPANY = 7, 
/**
 * Leverage
 */
exports.LEVERAGE_TYPE_1 = 1, exports.LEVERAGE_TYPE_10 = 10, exports.LEVERAGE_TYPE_20 = 20, exports.LEVERAGE_TYPE_25 = 25, exports.LEVERAGE_TYPE_50 = 50, exports.LEVERAGE_TYPE_100 = 100, 
/**
 * USER
 */
exports.USER_FETCH_TYPE_SLIM = 0, exports.USER_FETCH_TYPE_FULL = 1, exports.USER_FETCH_TYPE_PROFILE_SETTINGS = 2, exports.USER_FETCH_TYPE_ACCOUNT_DETAILS = 3, exports.USER_GENDER_UNKNOWN = 0, exports.USER_GENDER_MALE = 1, exports.USER_GENDER_FEMALE = 2, exports.USER_GENDER_OTHER = 3, 
/**
 * REDIS
 */
exports.REDIS_USER_PREFIX = 'user_', 
/**
 * EVENTS
 */
exports.CUSTOM_EVENT_TYPE_UNKNOWN = 0, exports.CUSTOM_EVENT_TYPE_ALARM = 1, exports.CUSTOM_EVENT_TYPE_ALARM_NEW = 2, exports.CUSTOM_EVENT_TYPE_PRICE = 10, 
/**
 * ALARMS
 */
exports.ALARM_TRIGGER_TYPE_PRICE = 1, exports.ALARM_TRIGGER_TYPE_PERCENTAGE = 2, exports.ALARM_TRIGGER_DIRECTION_UP = 1, exports.ALARM_TRIGGER_DIRECTION_DOWN = 2, 
/**
 * CANDLES
 */
exports.CANDLE_DEFAULT_ROW_LENGTH = 6;
//# sourceMappingURL=constants.js.map