export const symbols = [
    {
        "displayName": "Australia 200",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 200,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "AU200_AUD"
    },
    {
        "displayName": "AUD/CAD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "AUD_CAD"
    },
    {
        "displayName": "AUD/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "AUD_CHF"
    },
    {
        "displayName": "AUD/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "AUD_HKD"
    },
    {
        "displayName": "AUD/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "AUD_JPY"
    },
    {
        "displayName": "AUD/NZD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "AUD_NZD"
    },
    {
        "displayName": "AUD/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "AUD_SGD"
    },
    {
        "displayName": "AUD/USD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "AUD_USD"
    },
    {
        "displayName": "Brent Crude Oil",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "BCO_USD"
    },
    {
        "displayName": "CAD/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "CAD_CHF"
    },
    {
        "displayName": "CAD/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "CAD_HKD"
    },
    {
        "displayName": "CAD/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "CAD_JPY"
    },
    {
        "displayName": "CAD/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "CAD_SGD"
    },
    {
        "displayName": "Swiss 20",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 100,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": true,
        "name": "CH20_CHF"
    },
    {
        "displayName": "CHF/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "CHF_HKD"
    },
    {
        "displayName": "CHF/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "CHF_JPY"
    },
    {
        "displayName": "CHF/ZAR",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "CHF_ZAR"
    },
    {
        "displayName": "China A50",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 100,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "CN50_USD"
    },
    {
        "displayName": "Corn",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 150000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.033333,
        "halted": false,
        "name": "CORN_USD"
    },
    {
        "displayName": "Bund",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 6000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "DE10YB_EUR"
    },
    {
        "displayName": "Germany 30",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 25,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "DE30_EUR"
    },
    {
        "displayName": "Europe 50",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 300,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "EU50_EUR"
    },
    {
        "displayName": "EUR/AUD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_AUD"
    },
    {
        "displayName": "EUR/CAD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_CAD"
    },
    {
        "displayName": "EUR/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_CHF"
    },
    {
        "displayName": "EUR/CZK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "EUR_CZK"
    },
    {
        "displayName": "EUR/DKK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_DKK"
    },
    {
        "displayName": "EUR/GBP",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_GBP"
    },
    {
        "displayName": "EUR/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "EUR_HKD"
    },
    {
        "displayName": "EUR/HUF",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "EUR_HUF"
    },
    {
        "displayName": "EUR/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_JPY"
    },
    {
        "displayName": "EUR/NOK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_NOK"
    },
    {
        "displayName": "EUR/NZD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_NZD"
    },
    {
        "displayName": "EUR/PLN",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "EUR_PLN"
    },
    {
        "displayName": "EUR/SEK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_SEK"
    },
    {
        "displayName": "EUR/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "EUR_SGD"
    },
    {
        "displayName": "EUR/TRY",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "EUR_TRY"
    },
    {
        "displayName": "EUR/USD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "EUR_USD"
    },
    {
        "displayName": "EUR/ZAR",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "EUR_ZAR"
    },
    {
        "displayName": "France 40",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 200,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "FR40_EUR"
    },
    {
        "displayName": "GBP/AUD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "GBP_AUD"
    },
    {
        "displayName": "GBP/CAD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "GBP_CAD"
    },
    {
        "displayName": "GBP/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "GBP_CHF"
    },
    {
        "displayName": "GBP/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "GBP_HKD"
    },
    {
        "displayName": "GBP/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "GBP_JPY"
    },
    {
        "displayName": "GBP/NZD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "GBP_NZD"
    },
    {
        "displayName": "GBP/PLN",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "GBP_PLN"
    },
    {
        "displayName": "GBP/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "GBP_SGD"
    },
    {
        "displayName": "GBP/USD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "GBP_USD"
    },
    {
        "displayName": "GBP/ZAR",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "GBP_ZAR"
    },
    {
        "displayName": "Hong Kong 33",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 400,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "HK33_HKD"
    },
    {
        "displayName": "HKD/JPY",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "HKD_JPY"
    },
    {
        "displayName": "India 50",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 100,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "IN50_USD"
    },
    {
        "displayName": "Japan 225",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 100,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "JP225_USD"
    },
    {
        "displayName": "US Nas 100",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 400,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "NAS100_USD"
    },
    {
        "displayName": "Natural Gas",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 250000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "NATGAS_USD"
    },
    {
        "displayName": "Netherlands 25",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "NL25_EUR"
    },
    {
        "displayName": "NZD/CAD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "NZD_CAD"
    },
    {
        "displayName": "NZD/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "NZD_CHF"
    },
    {
        "displayName": "NZD/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "NZD_HKD"
    },
    {
        "displayName": "NZD/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "NZD_JPY"
    },
    {
        "displayName": "NZD/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "NZD_SGD"
    },
    {
        "displayName": "NZD/USD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "NZD_USD"
    },
    {
        "displayName": "Singapore 30",
        "pip": "0.1",
        "precision": "0.01",
        "maxTradeUnits": 300,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "SG30_SGD"
    },
    {
        "displayName": "SGD/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "SGD_CHF"
    },
    {
        "displayName": "SGD/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "SGD_HKD"
    },
    {
        "displayName": "SGD/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "SGD_JPY"
    },
    {
        "displayName": "Soybeans",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 60000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.033333,
        "halted": false,
        "name": "SOYBN_USD"
    },
    {
        "displayName": "US SPX 500",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 800,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "SPX500_USD"
    },
    {
        "displayName": "Sugar",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 4000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.033333,
        "halted": false,
        "name": "SUGAR_USD"
    },
    {
        "displayName": "TRY/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "TRY_JPY"
    },
    {
        "displayName": "Taiwan Index",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 100,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "TWIX_USD"
    },
    {
        "displayName": "UK 100",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 20,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "UK100_GBP"
    },
    {
        "displayName": "UK 10Y Gilt",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 6000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "UK10YB_GBP"
    },
    {
        "displayName": "US Russ 2000",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 1000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "US2000_USD"
    },
    {
        "displayName": "US Wall St 30",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 100,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "US30_USD"
    },
    {
        "displayName": "US 2Y T-Note",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 6000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "USB02Y_USD"
    },
    {
        "displayName": "US 5Y T-Note",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 6000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "USB05Y_USD"
    },
    {
        "displayName": "US 10Y T-Note",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 6000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "USB10Y_USD"
    },
    {
        "displayName": "US T-Bond",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 6000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "USB30Y_USD"
    },
    {
        "displayName": "USD/CAD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "USD_CAD"
    },
    {
        "displayName": "USD/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "USD_CHF"
    },
    {
        "displayName": "USD/CNH",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_CNH"
    },
    {
        "displayName": "USD/CZK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_CZK"
    },
    {
        "displayName": "USD/DKK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "USD_DKK"
    },
    {
        "displayName": "USD/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "USD_HKD"
    },
    {
        "displayName": "USD/HUF",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_HUF"
    },
    {
        "displayName": "USD/INR",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_INR"
    },
    {
        "displayName": "USD/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "USD_JPY"
    },
    {
        "displayName": "USD/MXN",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_MXN"
    },
    {
        "displayName": "USD/NOK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "USD_NOK"
    },
    {
        "displayName": "USD/PLN",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_PLN"
    },
    {
        "displayName": "USD/SAR",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_SAR"
    },
    {
        "displayName": "USD/SEK",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "USD_SEK"
    },
    {
        "displayName": "USD/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "USD_SGD"
    },
    {
        "displayName": "USD/THB",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_THB"
    },
    {
        "displayName": "USD/TRY",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_TRY"
    },
    {
        "displayName": "USD/ZAR",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "USD_ZAR"
    },
    {
        "displayName": "Wheat",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 150000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.033333,
        "halted": false,
        "name": "WHEAT_USD"
    },
    {
        "displayName": "West Texas Oil",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "WTICO_USD"
    },
    {
        "displayName": "Silver/AUD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_AUD"
    },
    {
        "displayName": "Silver/CAD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_CAD"
    },
    {
        "displayName": "Silver/CHF",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_CHF"
    },
    {
        "displayName": "Silver/EUR",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_EUR"
    },
    {
        "displayName": "Silver/GBP",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_GBP"
    },
    {
        "displayName": "Silver/HKD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_HKD"
    },
    {
        "displayName": "Silver/JPY",
        "pip": "1.0",
        "precision": "0.1",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "XAG_JPY"
    },
    {
        "displayName": "Silver/NZD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_NZD"
    },
    {
        "displayName": "Silver/SGD",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAG_SGD"
    },
    {
        "displayName": "Silver",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 50000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "XAG_USD"
    },
    {
        "displayName": "Gold/AUD",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_AUD"
    },
    {
        "displayName": "Gold/CAD",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_CAD"
    },
    {
        "displayName": "Gold/CHF",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_CHF"
    },
    {
        "displayName": "Gold/EUR",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "XAU_EUR"
    },
    {
        "displayName": "Gold/GBP",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "XAU_GBP"
    },
    {
        "displayName": "Gold/HKD",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_HKD"
    },
    {
        "displayName": "Gold/JPY",
        "pip": "10",
        "precision": "1.0",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_JPY"
    },
    {
        "displayName": "Gold/NZD",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_NZD"
    },
    {
        "displayName": "Gold/SGD",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_SGD"
    },
    {
        "displayName": "Gold",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.01,
        "halted": false,
        "name": "XAU_USD"
    },
    {
        "displayName": "Gold/Silver",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 2000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XAU_XAG"
    },
    {
        "displayName": "Copper",
        "pip": "0.0001",
        "precision": "0.00001",
        "maxTradeUnits": 250000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XCU_USD"
    },
    {
        "displayName": "Palladium",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 500,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XPD_USD"
    },
    {
        "displayName": "Platinum",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 500,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.05,
        "halted": false,
        "name": "XPT_USD"
    },
    {
        "displayName": "ZAR/JPY",
        "pip": "0.01",
        "precision": "0.001",
        "maxTradeUnits": 10000000,
        "maxTrailingStop": 10000,
        "minTrailingStop": 5,
        "marginRate": 0.02,
        "halted": false,
        "name": "ZAR_JPY"
    }
];