node {
    stage('Initialize') {
        echo 'Initializing...'
        def nodeHome = tool 'nodejs5'
        env.PATH="${env.PATH}:${nodeHome}/bin"
    }
    stage('get source') {
        checkout scm
        // git 'https://github.com/DutchKevv/TradeJS'
    }
    stage('install npm modules') {
        node -v
        npm i
    }
}