node {
    stage('clean workspace') {
        cleanWs()
    }
    stage('get source') {
        git branch: 'development', url: 'https://github.com/DutchKevv/TradeJS'
    }
    stage('install & build client') {
        dir('client') {
            sh 'npm i && npm run build'
        }
    }
    stage('install & build app') {
        dir('client-app') {
            sh 'npm i'
            sh './node_modules/.bin/cordova prepare android'
            sh 'npm run build-android'
        }
    }
}